version: '3.8'
services:
  php: 
    build: './docker/php'
    # user: ${UID:-1000}:${GID:-1000} # à commenter si l'user est root
    ports:
      - ${PHP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:80 -t .

  database:
      image: mariadb:10
      environment:
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD:-password}
          MYSQL_DATABASE: ${DB_DATABASE:-racoin}
          MYSQL_USER: ${DB_USER_NAME:-user}
          MYSQL_PASSWORD: ${DB_USER_PASSWORD:-password}
      ports:
          - "${DB_PORT:-3306}:3306"

  adminer:
      image: adminer
      ports:
          - '8088:8080'